### ISSUE TITLE
Consulta sobre datos de Chile

### ISSUE THREAD

**Issue by luisvidalvidal** [EL-BID/urbanpy#13]
Ayer asistía a Worshop que dieron por el BID, estoy tratando de cargar con datos de Chile, pero no funciona para Chile, si para otros países como Argentina o Perú:

pop_cl= up.download.hdx_fb_population('chile', 'full') 

Alguna sugerencia, y/o procedimiento para cargar manualmente, muchas gracias.

**Comment by Claudio9701** [comment]
Hola Luis! Muchas gracias por tu interés en UrbanPy. 

Sí! Tienes toda la razón, en la próxima versión de UrbanPy vamos a ofrecer una mejor alternativa para descargar los datos de cualquier país.

Hemos respondido cómo solucionar este impase en un [issue anterior](https://github.com/EL-BID/urbanpy/issues/2#issuecomment-669275483)

Para obtener la población de chile debes hacer lo siguiente:

1. Obtener el ID del recurso deseado desde [la página del dataset de población de Chile en HDX](https://data.humdata.org/dataset/chile-high-resolution-population-density-maps-demographic-estimates)

![image](https://user-images.githubusercontent.com/24416566/169732115-1803475a-72ca-4590-8bfd-9d772117655f.png)

2. En este link debemos extraer el identificador del recurso:

> https://data.humdata.org/dataset/ `dd47e052-02cc-4a3f-972a-421d600b3d85/resource/bb560451-9c50-4d57-8ff3-872fa260c102/download/chl_general_2020_csv.zip`

3. Finalmente utilizar la siguiente función `up.download.hdx_dataset` para obtener los datos:

```python
import urbanpy as up
pop = up.download.hdx_dataset(“dd47e052-02cc-4a3f-972a-421d600b3d85/resource/bb560451-9c50-4d57-8ff3-872fa260c102/download/chl_general_2020_csv.zip”) 
```
Espero que mi respuesta sea de ayuda 🙌🏽

**Comment by luisvidalvidal** [comment]
Muchas Gracias

Todo bien, ya pude cargar información, voy a trabajar con su API.

Valdivia, Chile..


Sa
[image: Valdivia Celdas H3 resolucion 8.png]
[image: Valdivia.png]

[image: Valdivia_Poblacion 2020.png]
Saludos
Luis Vidal
