### ISSUE TITLE
GDAL error when installing urbanpy

### ISSUE THREAD

**Issue by robcrystalornelas** [EL-BID/urbanpy#18]
Hi all 👋🏻 

As I was going through the urbanpy tutorial today in [UrbanPy_workshop.ipynb](https://colab.research.google.com/drive/1aRybqbsKerVAyJwsRYdSdvXz7V9F3XmN#scrollTo=41PqgGR8aP37) the step to install urbanpy:

`pip install urbanpy`

threw an error when trying to install the `gdal` dependency. The error was as follows.

> gdal_config_error: [Errno 2] No such file or directory: 'gdal-config'
Could not find gdal-config. Make sure you have installed the GDAL native library and development headers.

I found [this post](https://stackoverflow.com/questions/44898463/unable-to-install-gdal-in-python-3-6-1-in-macos-sierra) to help guide how to fix this in macOS by installing `gdal` with brew.

Once that ran, I could install urbanpy (using pipenv) via:

`pipenv install urbanpy`

However, after activating my pipenv, I still needed to run

`pip install urbanpy` in the jupyter notebook.

**Comment by Claudio9701** [comment]
Hello! Thanks for your issue!

Installing GIS deps can be hard. It is in our plans to add to the docs a installation tutorial for GIS deps similar to [this one](https://hackspaceperu.github.io/intro-data-analytics/guides/install_geopandas.html) but in english.

From what you said I will assume that you are running the jupyter notebook locally in a Mac.

Probably the jupyter notebook is connected to a Python kernel from the default system Python (where `urbanpy` was not installed). 

To import `urbanpy` from the virtualenv created by pipenv in your jupyter notebook you should connect it to a Python kernel from the virtualenv.

To do this you can either
- Launch the jupyter notebook inside your virtualenv. This will automatically connect your jupyter notebook to your virtualenv python.
- Or you can manually create a Python kernel with the Python installation from the virtualenv like [here](https://janakiev.com/blog/jupyter-virtual-envs/)

Hope this brief explanation is helpful!
