### ISSUE TITLE
Descarga de datos de poblacion limitada a ciertos paises

### ISSUE THREAD

**Issue by mposkus** [EL-BID/urbanpy#2]
**urbanpy.download.hdx_fb_population** solo permite descargar datos de algunos paises de latinoamerica - segun https://el-bid.github.io/urbanpy/urbanpy.download.html#urbanpy.download.hdx_fb_population solo Argentina, Bolivia, Brazil, Chile, Colombia, Ecuador, Paraguay, Peru y Uruguay. 

Hay forma de usar los datos de otros paises que estan disponibles en la pagina de humdata?

**Comment by Claudio9701** [comment]
Hola @mposkus! Gracias por reportar este issue. Tienes razón, por el momento sólo tenemos algunos países en esa función. Sí puedes descargar datos de otros países que estén disponibles en HDX usando la función [hdx_dataset](https://el-bid.github.io/urbanpy/urbanpy.download.html#urbanpy.download.hdx_dataset). Sería algo así:

```python
import urbanpy as up
pop = up.download.hdx_dataset(“2964b369-c10c-4b55-94a8-495de3fc9858/resource/728e9fe2-0707-491f-91d8-3dc8379d7a32/download/population_ken_2018-10-01.csv.zip”)
```

Otra forma un poco más larga sería que puedas agregar los países que necesitas al diccionario de recursos y hacer un pull request para que revisemos y aceptemos esta mejora.

Espero que mi respuesta te sirva. Saludos!

**Comment by a-regal** [comment]
Hola @mposkus, agregando al comentario de @Claudio9701, la función hdx_dataset toma el enlace del recurso hdx.

A lo que me refiero es que partiendo del enlace inicial a la data poblacional (usando Perú como ejemplo):

https://data.humdata.org/dataset/4e74db39-87f1-4383-9255-eaf8ebceb0c9/resource/317f1c39-8417-4bde-a076-99bd37feefce/download/population_per_2018-10-01.csv.zip

La función solo tomaría como parámetro:

4e74db39-87f1-4383-9255-eaf8ebceb0c9/resource/317f1c39-8417-4bde-a076-99bd37feefce/download/population_per_2018-10-01.csv.zip
