### ISSUE TITLE
routing.start_osrm_server  -- doesn´t start

### ISSUE THREAD

**Issue by AlonsoCortes** [EL-BID/urbanpy#4]
Hi! I'm recreating the demo notebook with the Mexico City, but I have an issue with "routing.start_osrm_server", I can't make this line of code to work, aparentlye it doesn't found a file, could you help me??

An image of the problem:
![image](https://user-images.githubusercontent.com/46790984/90193440-8c762600-dd8a-11ea-8ca3-9692146dfe8a.png)

**Comment by a-regal** [comment]
Hi! A couple of things that could be the issue:

1. Do you have docker desktop/tools installed? If so, it the docker daemon running?
2. The é is most likely the issue with wget, which may be the FileNotFoundError cause

Could you post the complete error please?

**Comment by AlonsoCortes** [comment]
Ok! thats the problem! I dont have docker in my computer hahaha
Time to install somethings!
Thanks!

**Comment by a-regal** [comment]
Just finished trying to reproduce this. With python > 3.7, docker desktop or tools and using `"mexico"` instead of `"méxico"` everything works fine.
